spring:
  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://localhost:5432/testdb
    username: testuser
    password: testpass
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        show_sql: true
    hibernate:
      ddl-auto: create
  data:
    mongodb:
#      uri: mongodb://192.168.0.69:27017
#      database: rawdata
#      username: admin
#      password: admin
#      uri: mongodb://admin:admin@192.168.0.69:27017/rawdata
#      authentication-database: admin
       uri: mongodb://admin:admin@192.168.0.69:27017/rawdata?authSource=admin
            